image: nixos/nix:latest

stages:
  - lint
  - buildandtest

variables:
  # Speeds up evaluation by using flakes and experimental features
  NIX_CONFIG: "experimental-features = nix-command flakes"
  
cache:
  # Cache for Cargo (target and .cargo)
  paths:
    - .cargo
    - target

before_script:
  - nix --version
  - nix flake metadata 

lint:
  stage: lint
  script:
    - nix develop .#default --command cargo clippy --all-targets --all-features -- -D warnings
    - nix develop .#default --command cargo fmt -- --check

test:
  stage: buildandtest
  script:
    - nix develop .#default --command cargo test

build:
  stage: buildandtest
  script:
    - nix build .#default
  artifacts:
    paths:
      - result/bin
