[package]
name = "sensei"
version = "0.1.0"
edition = "2024"

[dependencies]
lib = { path = "../lib" }
tokio = { version = "1.44.2", features = ["full"] }
anyhow = "1.0.98"
async-trait = "0.1.88"
argh = "0.1.12"
minifb = "0.25"
plotters = { version = "0.3.7", features = ["fontconfig-dlopen"] }
plotters-bitmap = "0.3.5"

[lints]
workspace = true
