device_id: 42
stype: IWL5300
source:
  type: Netlink
  group: 5
controller:
  type: Netlink
  params:
    interface: "wlp1s0"
    center_freq_mhz: 2412
    bandwidth_mhz: 20
    control_freq_mhz: null
    antenna_mask: 7
adapter:
  type: Iwl
  scale_csi: true
sinks:
  - type: File
    path: "/out/file.dat"
  - type: File
    path: "/dev/stdout"