- device_id: 0
  stype: TCP
  source: !Tcp
    target_addr: 127.0.0.1:8000
    device_id: 0
  controller: null
  adapter: null
  sinks:
    - !Tcp
      target_addr: 127.0.0.1:6969 
      device_id: 0