- metadata:
    name: Experiment1
    experiment_host: !Orchestrator
  stages:
    - name: "init"
      command_blocks:
        - commands:
            - !Connect
              target_addr: "127.0.0.1:42000"
            - !Connect
              target_addr: "127.0.0.1:12345"
            - !Configure
              target_addr: "127.0.0.1:12345"
              device_id: 0
              cfg_type: !Create
                cfg:
                  device_id: 0
                  stype: !Csv
                  source: !Csv
                    path: "scripts/csv_data.csv"
                    header: true
                    delay: 500
                    adapter: !Csv
                    output_to:
            - !StartAll
              target_addr: "127.0.0.1:12345"
            - !SubscribeTo
              target_addr: "127.0.0.1:42000"
              device_id: 0
              source_addr: "127.0.0.1:12345"
            - !Delay
              delay: 5000
            - !StopAll
              target_addr: "127.0.0.1:12345"
          delays:
            init_delay: 2000
            command_delay: 1000
            is_recurring: !NotRecurring