experiment:
metadata:
  name: Experiment1
  output_path: "output.csv"
stages:
  - name: "init"
    command_blocks:
        - commands:
            - !Connect
              target_addr: "127.0.0.1:8080"
          delays:
            init_delay: 2000
            is_recurring: !NotRecurring
  - name: "main"
    command_blocks:
      - commands:
          - !Connect
            target_addr: "127.0.0.1:8000"
          - !Subscribe
            target_addr: "127.0.0.1:8000"
            device_id: 0
          - !Delay
            delay: 5000
          - !Unsubscribe
            target_addr: "127.0.0.1:8000"
            device_id: 0
          - !Disconnect
            target_addr: "127.0.0.1:8000"
        delays:
          init_delay: 500
          command_delay: 200
          is_recurring: !Recurring
            recurrence_delay: 1000
            iterations: 5
      - commands:
          - !Connect
            target_addr: "127.0.0.1:8080"
          - !Subscribe
            target_addr: "127.0.0.1:8080"
            device_id: 0
          - !Delay
            delay: 5000
          - !Unsubscribe
            target_addr: "127.0.0.1:8080"
            device_id: 0
          - !Disconnect
            target_addr: "127.0.0.1:8080"
        delays:
          init_delay: 500
          command_delay: 200
          is_recurring: !Recurring
            recurrence_delay: 1000
            iterations: 5
  - name: "endstage"
    command_blocks:
      - commands:
        - !Disconnect
          target_addr: "127.0.0.1:8080"
        delays:
          is_recurring: !NotRecurring 